/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Process is up. Never touches dependencies.
         */
        get: operations["get_healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks Postgres, Redis, Qdrant reachability and Lyzr configuration. 503 when degraded.
         */
        get: operations["get_readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with the demo account
         * @description Sets an httpOnly `unsaid_session` cookie. Send later requests with `credentials: "include"`. Rate limited per IP.
         */
        post: operations["post_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie */
        post: operations["post_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal and the patients it can see */
        get: operations["get_v1_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a patient profile */
        post: operations["post_v1_users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a patient with activity counts */
        get: operations["get_v1_users_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update patient settings (context ON/OFF ablation toggle, assist mode) */
        patch: operations["patch_v1_users_id"];
        trace?: never;
    };
    "/v1/users/{id}/wordmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learned word map: substitutions and resolved utterances */
        get: operations["get_v1_users_id_wordmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caregiver insights: resolution rates and top substitutions */
        get: operations["get_v1_users_id_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulate/fragment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the ASSIST pipeline on a fragment
         * @description Equivalent to a patient fragment arriving from Omi. Returns once the first confirmation question has been created; follow progress on `/v1/stream`. A bare "yes"/"no" while a confirmation is pending answers it locally.
         */
        post: operations["post_v1_simulate_fragment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulate/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject transcript segments (ambient or patient) as if they came from Omi
         * @description Idempotent: re-sending a segment is counted in `duplicates` and does no further work.
         */
        post: operations["post_v1_simulate_segments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/confirmations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a confirmation (state machine snapshot) */
        get: operations["get_v1_confirmations_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/confirmations/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer yes/no to the current confirmation question
         * @description `yes` resolves with the current hypothesis; `no` advances to the next hypothesis, or ends with `assist.unresolved` after the last. Answering a non-PENDING confirmation is a no-op that returns its final state.
         */
        post: operations["post_v1_confirmations_id_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a synthesized question/sentence (MP3)
         * @description Public: browser `<audio>` cannot send headers. Ids are unguessable UUIDs.
         */
        get: operations["get_v1_audio_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events feed for one patient
         * @description Each frame is `event: <type>` + `data: <EventEnvelope JSON>`. See docs/FRONTEND_CONTRACT.md for every event type and the ASSIST trace lifecycle. Browsers: `new EventSource(url, { withCredentials: true })` with the session cookie, or `?api_key=` for scripts.
         */
        get: operations["get_v1_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipeline runs */
        get: operations["get_v1_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full trace of a run: steps, latencies, retrieval hits with scores */
        get: operations["get_v1_runs_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or semantically search a patient's memory facts */
        get: operations["get_v1_memory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/{pointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one memory fact (privacy control) */
        delete: operations["delete_v1_memory_pointId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Erase all memory and word-map vectors for a patient */
        post: operations["post_v1_memory_purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omi/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the Omi live path delivering?
         * @description Last segment time, source (OMI_REALTIME vs SIMULATED) and 5-minute counts.
         */
        get: operations["get_v1_omi_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript segments (recent, or by dedupe key for fact provenance) */
        get: operations["get_v1_segments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/omi/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Omi real-time transcript webhook
         * @description Body: `{ session_id, segments: [...] }` (a bare array is also accepted). Query: `uid`, optional `session_id`. Authenticated by the webhook secret (`?secret=`, `x-omi-secret` header, or `/webhooks/omi/transcript/{secret}`), not by the API key. Always 200 for unparseable payloads (raw body is stored). Duplicate segments are reported in `duplicates` and do no extra work.
         */
        post: operations["post_webhooks_omi_transcript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/omi/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Omi conversation-created (memory) webhook
         * @description Body is a finished conversation with `transcript_segments`. Runs the INGEST pipeline.
         */
        post: operations["post_webhooks_omi_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @example validation_error */
                code: string;
                message: string;
                requestId?: string;
                details?: unknown;
            };
        };
        User: {
            id: string;
            omiUid: string | null;
            displayName: string;
            /** @constant */
            role: "PATIENT";
            contextEnabled: boolean;
            /** @enum {string} */
            assistMode: "AUTO" | "ON" | "OFF";
            caregiverName: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UserDetail: {
            id: string;
            omiUid: string | null;
            displayName: string;
            /** @constant */
            role: "PATIENT";
            contextEnabled: boolean;
            /** @enum {string} */
            assistMode: "AUTO" | "ON" | "OFF";
            caregiverName: string | null;
            /** Format: date-time */
            createdAt: string;
            _count: {
                segments: number;
                runs: number;
                confirmations: number;
                wordMapEntries: number;
            };
        };
        Hypothesis: {
            intent: string;
            sentence: string;
            speaker_perspective_question: string;
            confidence: number;
            /** @default [] */
            evidenceIds: string[];
            reasoning: string;
        };
        Confirmation: {
            id: string;
            userId: string;
            runId: string;
            fragment: string;
            hypotheses: components["schemas"]["Hypothesis"][];
            currentIndex: number;
            question: string;
            questionAudio: string | null;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "REJECTED_ALL" | "EXPIRED";
            confirmedIdx: number | null;
            finalSentence: string | null;
            finalAudio: string | null;
            resolution: string | null;
            /** Format: date-time */
            createdAt: string;
            resolvedAt: string | null;
        };
        Step: {
            id: string;
            runId: string;
            /** @example retrieve_memory */
            node: string;
            agentId: string | null;
            /** @enum {string} */
            status: "RUNNING" | "COMPLETED" | "FAILED" | "SKIPPED";
            input: unknown;
            output: unknown | null;
            error: string | null;
            /** @description Qdrant hits (id, type, text, score) for retrieval nodes */
            retrieval: {
                [key: string]: unknown;
            }[] | null;
            latencyMs: number | null;
            /** @description ms from run start to this step start (shared timeline for parallel steps) */
            startOffsetMs: number;
            /** @description Sponsor/service tag: lyzr agent, qdrant collection, tts, redis or local */
            service: {
                /** @enum {string} */
                provider: "lyzr" | "qdrant" | "openai" | "tts" | "redis" | "local";
                name: string;
            };
            attempt: number;
            /** Format: date-time */
            startedAt: string;
            endedAt: string | null;
        };
        Run: {
            id: string;
            userId: string;
            /** @enum {string} */
            pipeline: "ASSIST" | "INGEST" | "LEARN";
            /** @enum {string} */
            status: "RUNNING" | "AWAITING_CONFIRMATION" | "SUCCEEDED" | "FAILED";
            input: unknown;
            output: unknown | null;
            contextUsed: boolean;
            /** Format: date-time */
            startedAt: string;
            endedAt: string | null;
        };
        WordMapEntry: {
            id: string;
            userId: string;
            saidToken: string;
            meantToken: string;
            /** @enum {string} */
            kind: "SUBSTITUTION" | "PHRASE" | "NAME_ALIAS";
            hits: number;
            /** Format: date-time */
            lastSeenAt: string;
            qdrantId: string;
        };
        MemoryFact: {
            id: string;
            userId?: string;
            type?: string;
            text?: string;
            entities?: string[];
            aliases?: string[];
            score?: number;
        } & {
            [key: string]: unknown;
        };
        Me: {
            principal: {
                /** @constant */
                type: "api_key";
            } | {
                /** @constant */
                type: "session";
                email: string;
                /** Format: date-time */
                expiresAt: string;
            };
            patients: {
                id: string;
                displayName: string;
                contextEnabled: boolean;
                /** @enum {string} */
                assistMode: "AUTO" | "ON" | "OFF";
            }[];
        };
        WordMap: {
            substitutions: components["schemas"]["WordMapEntry"][];
            resolvedUtterances: ({
                id: string | number;
                fragment: string;
                resolvedSentence: string;
                hits: number;
            } & {
                [key: string]: unknown;
            })[];
        };
        Insights: {
            userId: string;
            displayName: string;
            stats: {
                fragmentsCount: number;
                totalConfirmations: number;
                confirmedCount: number;
                firstTryCount: number;
                firstTryResolutionRate: number;
                overallResolutionRate: number;
            };
            topSubstitutions: components["schemas"]["WordMapEntry"][];
        };
        AnswerResult: {
            confirmation: components["schemas"]["Confirmation"];
            resolved: boolean;
            finalSentence?: string;
            finalAudio?: string;
            nextQuestion?: string;
            fallbackQuestion?: string;
        };
        AssistResult: {
            runId?: string;
            confirmationId?: string;
            resolved?: boolean;
            handledAsReply?: boolean;
        };
        RunDetail: {
            id: string;
            userId: string;
            /** @enum {string} */
            pipeline: "ASSIST" | "INGEST" | "LEARN";
            /** @enum {string} */
            status: "RUNNING" | "AWAITING_CONFIRMATION" | "SUCCEEDED" | "FAILED";
            input: unknown;
            output: unknown | null;
            contextUsed: boolean;
            /** Format: date-time */
            startedAt: string;
            endedAt: string | null;
            steps: components["schemas"]["Step"][];
            user: {
                id: string;
                displayName: string;
                contextEnabled: boolean;
                /** @enum {string} */
                assistMode: "AUTO" | "ON" | "OFF";
            };
        };
        /** @enum {string} */
        EventType: "segment.received" | "segment.classified" | "hypotheses.generated" | "run.started" | "step.started" | "step.completed" | "step.failed" | "memory.upserted" | "confirmation.asked" | "confirmation.answered" | "assist.resolved" | "assist.unresolved" | "confirmation.expired" | "wordmap.updated" | "run.completed";
        EventEnvelope: {
            type: components["schemas"]["EventType"];
            userId: string;
            runId?: string;
            /** Format: date-time */
            ts: string;
            data: {
                [key: string]: unknown;
            };
        };
        WebhookAck: {
            /** @constant */
            ok: true;
            received?: number;
            duplicates?: number;
            ignored?: boolean;
            reason?: string;
        };
        OmiStatus: {
            lastSegmentAt: string | null;
            lastSegmentSource: ("OMI_REALTIME" | "OMI_MEMORY" | "SIMULATED") | null;
            segmentsLast5Min: {
                OMI_REALTIME: number;
                OMI_MEMORY: number;
                SIMULATED: number;
            };
            lastRawWebhookAt: string | null;
            rawWebhooksLast5Min: number;
            webhookSecretConfigured: boolean;
        };
        Liveness: {
            /** @constant */
            status: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "degraded";
            mockExternals: boolean;
            /** @enum {string} */
            db: "ok" | "down";
            /** @enum {string} */
            redis: "ok" | "down";
            /** @enum {string} */
            qdrant: "ok" | "down";
            /** @example configured */
            lyzr: string;
        };
        Segment: {
            id: string;
            /** @description Matches `sourceSegmentIds` on memory facts */
            dedupeKey: string;
            sessionId: string;
            text: string;
            speaker: string | null;
            isUser: boolean;
            /** @enum {string} */
            source: "OMI_REALTIME" | "OMI_MEMORY" | "SIMULATED";
            kind: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    get_readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    post_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: {
                            email: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service unavailable / not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    get_v1_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["Me"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_v1_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName: string;
                    omiUid?: string;
                    caregiverName?: string;
                    contextEnabled?: boolean;
                    /** @enum {string} */
                    assistMode?: "AUTO" | "ON" | "OFF";
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["User"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_users_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["UserDetail"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    patch_v1_users_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                    caregiverName?: string;
                    contextEnabled?: boolean;
                    /** @enum {string} */
                    assistMode?: "AUTO" | "ON" | "OFF";
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["User"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_users_id_wordmap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Word map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["WordMap"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_users_id_insights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insights */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["Insights"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_v1_simulate_fragment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                    text: string;
                };
            };
        };
        responses: {
            /** @description Pipeline result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["AssistResult"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_v1_simulate_segments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                    sessionId?: string;
                    segments: {
                        text: string;
                        /** @default false */
                        isUser?: boolean;
                        speaker?: string | null;
                        start?: number | null;
                        end?: number | null;
                    }[];
                };
            };
        };
        responses: {
            /** @description Processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        processed: number;
                        duplicates: number;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_confirmations_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["Confirmation"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_v1_confirmations_id_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    answer: "yes" | "no";
                };
            };
        };
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["AnswerResult"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_audio_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description audio/mpeg */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_stream: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of EventEnvelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["EventEnvelope"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_runs: {
        parameters: {
            query?: {
                userId?: string;
                pipeline?: "ASSIST" | "INGEST" | "LEARN";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: {
                            id: string;
                            userId: string;
                            /** @enum {string} */
                            pipeline: "ASSIST" | "INGEST" | "LEARN";
                            /** @enum {string} */
                            status: "RUNNING" | "AWAITING_CONFIRMATION" | "SUCCEEDED" | "FAILED";
                            input: unknown;
                            output: unknown | null;
                            contextUsed: boolean;
                            /** Format: date-time */
                            startedAt: string;
                            endedAt: string | null;
                            _count: {
                                steps: number;
                            };
                        }[];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_runs_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["RunDetail"];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_memory: {
        parameters: {
            query: {
                userId: string;
                q?: string;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["MemoryFact"][];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_v1_memory_pointId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                pointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        deleted: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_v1_memory_purge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                };
            };
        };
        responses: {
            /** @description Purged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        /** @constant */
                        purged: true;
                        userId: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_omi_status: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["OmiStatus"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_v1_segments: {
        parameters: {
            query: {
                userId: string;
                ids?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Segments, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        data: components["schemas"]["Segment"][];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_webhooks_omi_transcript: {
        parameters: {
            query?: {
                uid?: string;
                session_id?: string;
                secret?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[] | ({
                    segments: {
                        [key: string]: unknown;
                    }[];
                } & {
                    [key: string]: unknown;
                });
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    post_webhooks_omi_memory: {
        parameters: {
            query?: {
                uid?: string;
                session_id?: string;
                secret?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    transcript_segments?: {
                        [key: string]: unknown;
                    }[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
